# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: 'go.mod: '
    groups:
      # Split out any heavy-weights
      most-deps:
        exclude-patterns:
          - 'k8s.io/*'
          - 'sigs.k8s.io/*'
      kubernetes:
        patterns:
          - 'k8s.io/*'
          - 'sigs.k8s.io/*'
