apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bar
  namespace: foo
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
    template:
      spec:
        containers:
          - name: web
            image: ubuntu:latest
            command:
              - /bin/sh
              - -c
              - date; echo "Hello, World!"
