apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  namespace: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
        - name: web
          image: nginx:latest
          ports:
            - containerPort: 8080
