// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: data/v1/data.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *anypb.Any             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	SignedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_data_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessage() *anypb.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Envelope) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Envelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Envelope) GetSignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SignedAt
	}
	return nil
}

type Bytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bytes) Reset() {
	*x = Bytes{}
	mi := &file_data_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bytes) ProtoMessage() {}

func (x *Bytes) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bytes.ProtoReflect.Descriptor instead.
func (*Bytes) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *Bytes) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type MultipartBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*MultipartBytes_Part `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipartBytes) Reset() {
	*x = MultipartBytes{}
	mi := &file_data_v1_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipartBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartBytes) ProtoMessage() {}

func (x *MultipartBytes) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartBytes.ProtoReflect.Descriptor instead.
func (*MultipartBytes) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{2}
}

func (x *MultipartBytes) GetParts() []*MultipartBytes_Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

type UnixMeta struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Permission    string                            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	OwnerName     string                            `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	OwnerId       int32                             `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	GroupName     string                            `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupId       int32                             `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Attrs         []*UnixMeta_UnixExtendedAttribute `protobuf:"bytes,6,rep,name=attrs,proto3" json:"attrs,omitempty"`
	Times         *UnixMeta_UnixExtendedTimestamps  `protobuf:"bytes,7,opt,name=times,proto3" json:"times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnixMeta) Reset() {
	*x = UnixMeta{}
	mi := &file_data_v1_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnixMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixMeta) ProtoMessage() {}

func (x *UnixMeta) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnixMeta.ProtoReflect.Descriptor instead.
func (*UnixMeta) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{3}
}

func (x *UnixMeta) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *UnixMeta) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *UnixMeta) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *UnixMeta) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *UnixMeta) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UnixMeta) GetAttrs() []*UnixMeta_UnixExtendedAttribute {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *UnixMeta) GetTimes() *UnixMeta_UnixExtendedTimestamps {
	if x != nil {
		return x.Times
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      *UnixMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Multipart     *MultipartBytes        `protobuf:"bytes,3,opt,name=multipart,proto3" json:"multipart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_data_v1_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{4}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetMetadata() *UnixMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *File) GetMultipart() *MultipartBytes {
	if x != nil {
		return x.Multipart
	}
	return nil
}

type Directory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      *UnixMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Directories   []*Directory           `protobuf:"bytes,3,rep,name=directories,proto3" json:"directories,omitempty"`
	Files         []*File                `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directory) Reset() {
	*x = Directory{}
	mi := &file_data_v1_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directory) ProtoMessage() {}

func (x *Directory) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directory.ProtoReflect.Descriptor instead.
func (*Directory) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{5}
}

func (x *Directory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Directory) GetMetadata() *UnixMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Directory) GetDirectories() []*Directory {
	if x != nil {
		return x.Directories
	}
	return nil
}

func (x *Directory) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type MultipartBytes_Part struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlobRef       string                 `protobuf:"bytes,1,opt,name=blob_ref,json=blobRef,proto3" json:"blob_ref,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipartBytes_Part) Reset() {
	*x = MultipartBytes_Part{}
	mi := &file_data_v1_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipartBytes_Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartBytes_Part) ProtoMessage() {}

func (x *MultipartBytes_Part) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartBytes_Part.ProtoReflect.Descriptor instead.
func (*MultipartBytes_Part) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{2, 0}
}

func (x *MultipartBytes_Part) GetBlobRef() string {
	if x != nil {
		return x.BlobRef
	}
	return ""
}

func (x *MultipartBytes_Part) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MultipartBytes_Part) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UnixMeta_UnixExtendedAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnixMeta_UnixExtendedAttribute) Reset() {
	*x = UnixMeta_UnixExtendedAttribute{}
	mi := &file_data_v1_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnixMeta_UnixExtendedAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixMeta_UnixExtendedAttribute) ProtoMessage() {}

func (x *UnixMeta_UnixExtendedAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnixMeta_UnixExtendedAttribute.ProtoReflect.Descriptor instead.
func (*UnixMeta_UnixExtendedAttribute) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UnixMeta_UnixExtendedAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnixMeta_UnixExtendedAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UnixMeta_UnixExtendedTimestamps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ModifyTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	AccessTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=access_time,json=accessTime,proto3" json:"access_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnixMeta_UnixExtendedTimestamps) Reset() {
	*x = UnixMeta_UnixExtendedTimestamps{}
	mi := &file_data_v1_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnixMeta_UnixExtendedTimestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixMeta_UnixExtendedTimestamps) ProtoMessage() {}

func (x *UnixMeta_UnixExtendedTimestamps) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnixMeta_UnixExtendedTimestamps.ProtoReflect.Descriptor instead.
func (*UnixMeta_UnixExtendedTimestamps) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{3, 1}
}

func (x *UnixMeta_UnixExtendedTimestamps) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *UnixMeta_UnixExtendedTimestamps) GetModifyTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifyTime
	}
	return nil
}

func (x *UnixMeta_UnixExtendedTimestamps) GetAccessTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTime
	}
	return nil
}

var File_data_v1_data_proto protoreflect.FileDescriptor

const file_data_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x12data/v1/data.proto\x12\x0fsamples.data.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n" +
	"\bEnvelope\x12.\n" +
	"\amessage\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\amessage\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x127\n" +
	"\tsigned_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bsignedAtJ\x04\b\x01\x10\x02\"!\n" +
	"\x05Bytes\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"\x9b\x01\n" +
	"\x0eMultipartBytes\x12:\n" +
	"\x05parts\x18\x01 \x03(\v2$.samples.data.v1.MultipartBytes.PartR\x05parts\x1aM\n" +
	"\x04Part\x12\x19\n" +
	"\bblob_ref\x18\x01 \x01(\tR\ablobRef\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"\xc2\x04\n" +
	"\bUnixMeta\x12\x1e\n" +
	"\n" +
	"permission\x18\x01 \x01(\tR\n" +
	"permission\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tR\townerName\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x05R\aownerId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x04 \x01(\tR\tgroupName\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\x05R\agroupId\x12E\n" +
	"\x05attrs\x18\x06 \x03(\v2/.samples.data.v1.UnixMeta.UnixExtendedAttributeR\x05attrs\x12F\n" +
	"\x05times\x18\a \x01(\v20.samples.data.v1.UnixMeta.UnixExtendedTimestampsR\x05times\x1aA\n" +
	"\x15UnixExtendedAttribute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x1a\xcf\x01\n" +
	"\x16UnixExtendedTimestamps\x12;\n" +
	"\vcreate_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vmodify_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifyTime\x12;\n" +
	"\vaccess_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"accessTime\"\x90\x01\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\bmetadata\x18\x02 \x01(\v2\x19.samples.data.v1.UnixMetaR\bmetadata\x12=\n" +
	"\tmultipart\x18\x03 \x01(\v2\x1f.samples.data.v1.MultipartBytesR\tmultipart\"\xc1\x01\n" +
	"\tDirectory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\bmetadata\x18\x02 \x01(\v2\x19.samples.data.v1.UnixMetaR\bmetadata\x12<\n" +
	"\vdirectories\x18\x03 \x03(\v2\x1a.samples.data.v1.DirectoryR\vdirectories\x12+\n" +
	"\x05files\x18\x04 \x03(\v2\x15.samples.data.v1.FileR\x05filesB%Z#github.com/ripta/rt/samples/data/v1b\x06proto3"

var (
	file_data_v1_data_proto_rawDescOnce sync.Once
	file_data_v1_data_proto_rawDescData []byte
)

func file_data_v1_data_proto_rawDescGZIP() []byte {
	file_data_v1_data_proto_rawDescOnce.Do(func() {
		file_data_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_v1_data_proto_rawDesc), len(file_data_v1_data_proto_rawDesc)))
	})
	return file_data_v1_data_proto_rawDescData
}

var file_data_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_data_v1_data_proto_goTypes = []any{
	(*Envelope)(nil),                        // 0: samples.data.v1.Envelope
	(*Bytes)(nil),                           // 1: samples.data.v1.Bytes
	(*MultipartBytes)(nil),                  // 2: samples.data.v1.MultipartBytes
	(*UnixMeta)(nil),                        // 3: samples.data.v1.UnixMeta
	(*File)(nil),                            // 4: samples.data.v1.File
	(*Directory)(nil),                       // 5: samples.data.v1.Directory
	(*MultipartBytes_Part)(nil),             // 6: samples.data.v1.MultipartBytes.Part
	(*UnixMeta_UnixExtendedAttribute)(nil),  // 7: samples.data.v1.UnixMeta.UnixExtendedAttribute
	(*UnixMeta_UnixExtendedTimestamps)(nil), // 8: samples.data.v1.UnixMeta.UnixExtendedTimestamps
	(*anypb.Any)(nil),                       // 9: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),           // 10: google.protobuf.Timestamp
}
var file_data_v1_data_proto_depIdxs = []int32{
	9,  // 0: samples.data.v1.Envelope.message:type_name -> google.protobuf.Any
	10, // 1: samples.data.v1.Envelope.signed_at:type_name -> google.protobuf.Timestamp
	6,  // 2: samples.data.v1.MultipartBytes.parts:type_name -> samples.data.v1.MultipartBytes.Part
	7,  // 3: samples.data.v1.UnixMeta.attrs:type_name -> samples.data.v1.UnixMeta.UnixExtendedAttribute
	8,  // 4: samples.data.v1.UnixMeta.times:type_name -> samples.data.v1.UnixMeta.UnixExtendedTimestamps
	3,  // 5: samples.data.v1.File.metadata:type_name -> samples.data.v1.UnixMeta
	2,  // 6: samples.data.v1.File.multipart:type_name -> samples.data.v1.MultipartBytes
	3,  // 7: samples.data.v1.Directory.metadata:type_name -> samples.data.v1.UnixMeta
	5,  // 8: samples.data.v1.Directory.directories:type_name -> samples.data.v1.Directory
	4,  // 9: samples.data.v1.Directory.files:type_name -> samples.data.v1.File
	10, // 10: samples.data.v1.UnixMeta.UnixExtendedTimestamps.create_time:type_name -> google.protobuf.Timestamp
	10, // 11: samples.data.v1.UnixMeta.UnixExtendedTimestamps.modify_time:type_name -> google.protobuf.Timestamp
	10, // 12: samples.data.v1.UnixMeta.UnixExtendedTimestamps.access_time:type_name -> google.protobuf.Timestamp
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_data_v1_data_proto_init() }
func file_data_v1_data_proto_init() {
	if File_data_v1_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_v1_data_proto_rawDesc), len(file_data_v1_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_v1_data_proto_goTypes,
		DependencyIndexes: file_data_v1_data_proto_depIdxs,
		MessageInfos:      file_data_v1_data_proto_msgTypes,
	}.Build()
	File_data_v1_data_proto = out.File
	file_data_v1_data_proto_goTypes = nil
	file_data_v1_data_proto_depIdxs = nil
}
